/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import islandScene from '../assets/3D/island.glb';
import { useFrame } from "@react-three/fiber";
export function Island(props) {
  const islandRef = useRef();
  const { nodes, materials, animations } = useGLTF(islandScene);
  const { actions } = useAnimations(animations, islandRef);

  // useFrame(()=>{
  //   islandRef.current.rotation.y-=0.005;
  // })

  return (
    <group ref={islandRef} {...props} dispose={null}>
      <group name="Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group
            name="ac592a3c12cb4096bd27ee6037a8ea76fbx"
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.01}
          >
            <group name="RootNode">
              <group name="group1" rotation={[0, Math.PI / 4, 0]}>
                <group name="pCube17">
                  <mesh
                    name="pCube17_Leaf_Green_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCube17_Leaf_Green_0.geometry}
                    material={materials.Leaf_Green}
                  />
                </group>
                <group name="pCube18">
                  <mesh
                    name="pCube18_Leaf_Green_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCube18_Leaf_Green_0.geometry}
                    material={materials.Leaf_Green}
                  />
                </group>
                <group name="pCube24">
                  <mesh
                    name="pCube24_Leaf_Green_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCube24_Leaf_Green_0.geometry}
                    material={materials.Leaf_Green}
                  />
                </group>
                <group name="sweep7">
                  <mesh
                    name="sweep7_Tree_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.sweep7_Tree_0.geometry}
                    material={materials.Tree}
                  />
                </group>
              </group>
              <group name="group2" position={[0, 0, -1484.57666016]}>
                <group name="pCube19">
                  <mesh
                    name="pCube19_Leaf_Green_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCube19_Leaf_Green_0.geometry}
                    material={materials.Leaf_Green}
                  />
                </group>
                <group name="pCube20">
                  <mesh
                    name="pCube20_Leaf_Green_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCube20_Leaf_Green_0.geometry}
                    material={materials.Leaf_Green}
                  />
                </group>
              </group>
              <group name="group3" position={[0, 0, -2561.05224609]}>
                <group name="group5">
                  <group
                    name="group10"
                    position={[1964.78308105, 285.02474976, -5760.44433594]}
                    rotation={[0, -1.57053468, 0]}
                  >
                    <group
                      name="pCube14"
                      position={[0.00168914, -0.00003052, -0.00010264]}
                    >
                      <mesh
                        name="pCube14_Leaf_Green_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.pCube14_Leaf_Green_0.geometry}
                        material={materials.Leaf_Green}
                        position={[0.00071258, -0.00003052, -0.00010264]}
                      />
                    </group>
                    <group
                      name="pCube15"
                      position={[0.00168914, -0.00003052, -0.00010264]}
                    >
                      <mesh
                        name="pCube15_Leaf_Green_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.pCube15_Leaf_Green_0.geometry}
                        material={materials.Leaf_Green}
                        position={[0.00071258, -0.00003052, -0.00010264]}
                      />
                    </group>
                    <group
                      name="sweep3"
                      position={[0.00168914, -0.00003052, -0.00010264]}
                    >
                      <mesh
                        name="sweep3_Tree_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.sweep3_Tree_0.geometry}
                        material={materials.Tree}
                        position={[0.00071258, -0.00003052, -0.00010264]}
                      />
                    </group>
                  </group>
                </group>
                <group
                  name="group6"
                  position={[-9122.60546875, 0, -5640.29785156]}
                  rotation={[0, -Math.PI / 4, 0]}
                >
                  <group
                    name="pCube14001"
                    position={[-0.00146484, 0, -0.00054932]}
                  >
                    <mesh
                      name="pCube14_Leaf_Green_0001"
                      castShadow
                      receiveShadow
                      geometry={nodes.pCube14_Leaf_Green_0001.geometry}
                      material={materials.Leaf_Green}
                      position={[-0.00146484, 0, 0.00036621]}
                    />
                  </group>
                  <group
                    name="pCube15001"
                    position={[-0.00146484, 0, -0.00054932]}
                  >
                    <mesh
                      name="pCube15_Leaf_Green_0001"
                      castShadow
                      receiveShadow
                      geometry={nodes.pCube15_Leaf_Green_0001.geometry}
                      material={materials.Leaf_Green}
                      position={[-0.00146484, 0, 0.00036621]}
                    />
                  </group>
                  <group
                    name="pCube22"
                    position={[-0.00146484, 0, -0.00054932]}
                  >
                    <mesh
                      name="pCube22_Leaf_Green_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.pCube22_Leaf_Green_0.geometry}
                      material={materials.Leaf_Green}
                      position={[-0.00146484, 0, 0.00036621]}
                    />
                  </group>
                  <group
                    name="sweep3001"
                    position={[-0.00146484, 0, -0.00054932]}
                  >
                    <mesh
                      name="sweep3_Tree_0001"
                      castShadow
                      receiveShadow
                      geometry={nodes.sweep3_Tree_0001.geometry}
                      material={materials.Tree}
                      position={[-0.00146484, 0, 0.00036621]}
                    />
                  </group>
                </group>
              </group>
              <group name="group4" position={[0, 0, -3732.9152832]}>
                <group name="group7" position={[0, 0, 0.00024414]}>
                  <group name="pCube21">
                    <mesh
                      name="pCube21_Leaf_Green_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.pCube21_Leaf_Green_0.geometry}
                      material={materials.Leaf_Green}
                      position={[0, 0, 0.00024414]}
                    />
                  </group>
                </group>
                <group
                  name="group8"
                  position={[-11468.61523438, 0, -3380.58154297]}
                  rotation={[0, -Math.PI / 4, 0]}
                >
                  <group name="pCube12" position={[0, 0, 0.00048828]}>
                    <mesh
                      name="pCube12_Leaf_Green_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.pCube12_Leaf_Green_0.geometry}
                      material={materials.Leaf_Green}
                      position={[-0.00146484, 0, 0.00048828]}
                    />
                  </group>
                  <group name="pCube16" position={[0, 0, 0.00048828]}>
                    <mesh
                      name="pCube16_Leaf_Green_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.pCube16_Leaf_Green_0.geometry}
                      material={materials.Leaf_Green}
                      position={[-0.00146484, 0, 0.00048828]}
                    />
                  </group>
                  <group name="pCube23" position={[0, 0, 0.00048828]}>
                    <mesh
                      name="pCube23_Leaf_Green_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.pCube23_Leaf_Green_0.geometry}
                      material={materials.Leaf_Green}
                      position={[-0.00146484, 0, 0.00048828]}
                    />
                  </group>
                  <group name="sweep2" position={[0, 0, 0.00048828]}>
                    <mesh
                      name="sweep2_Tree_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.sweep2_Tree_0.geometry}
                      material={materials.Tree}
                      position={[-0.00146484, 0, 0.00048828]}
                    />
                  </group>
                </group>
              </group>
              <group name="pCube10">
                <mesh
                  name="pCube10_Stone_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.pCube10_Stone_0.geometry}
                  material={materials.Stone}
                />
              </group>
              <group name="pCube5">
                <mesh
                  name="pCube5_Stone_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.pCube5_Stone_0.geometry}
                  material={materials.Stone}
                />
              </group>
              <group name="pCube6">
                <mesh
                  name="pCube6_Stone_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.pCube6_Stone_0.geometry}
                  material={materials.Stone}
                />
              </group>
              <group name="pCube7">
                <mesh
                  name="pCube7_Stone_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.pCube7_Stone_0.geometry}
                  material={materials.Stone}
                />
              </group>
              <group name="pCube8">
                <mesh
                  name="pCube8_Stone_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.pCube8_Stone_0.geometry}
                  material={materials.Stone}
                />
              </group>
              <group name="pCube9">
                <mesh
                  name="pCube9_Stone_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.pCube9_Stone_0.geometry}
                  material={materials.Stone}
                />
              </group>
              <group name="pDisc1">
                <mesh
                  name="pDisc1_Grass_2_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.pDisc1_Grass_2_0.geometry}
                  material={materials.Grass_2}
                />
                <mesh
                  name="pDisc1_Mountain_Stone_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.pDisc1_Mountain_Stone_0.geometry}
                  material={materials.Mountain_Stone}
                />
                <mesh
                  name="pDisc1_Pastel_Green_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.pDisc1_Pastel_Green_0.geometry}
                  material={materials.Pastel_Green}
                />
                <mesh
                  name="pDisc1_Sand_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.pDisc1_Sand_0.geometry}
                  material={materials.Sand}
                />
                <mesh
                  name="pDisc1_Snow_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.pDisc1_Snow_0.geometry}
                  material={materials.Snow}
                />
                <mesh
                  name="pDisc1_Stone_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.pDisc1_Stone_0.geometry}
                  material={materials.Stone}
                />
              </group>
              <group name="pDisc3">
                <mesh
                  name="pDisc3_phong5_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.pDisc3_phong5_0.geometry}
                  material={materials.phong5}
                />
              </group>
              <group name="pDisc4">
                <mesh
                  name="pDisc4_phong5_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.pDisc4_phong5_0.geometry}
                  material={materials.phong5}
                />
              </group>
            </group>
          </group>
        </group>
        <group name="LP2fbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="RootNode001" position={[-0.00000696, 0, 0.00000231]}>
            <group name="LP" position={[-0.00000458, 0, 0.00000231]}>
              <group name="LP1" position={[-0.00000553, 0, 0]}>
                <mesh
                  name="LP1_house_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.LP1_house_0.geometry}
                  material={materials.house}
                  position={[-0.00000458, 0, 0]}
                />
              </group>
              <group name="LP10" position={[-0.00000553, 0, 0]}>
                <mesh
                  name="LP10_karkas_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.LP10_karkas_0.geometry}
                  material={materials.karkas}
                  position={[-0.00000458, 0, 0]}
                />
              </group>
              <group name="LP11" position={[-0.00000553, 0, 0]}>
                <mesh
                  name="LP11_karkas_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.LP11_karkas_0.geometry}
                  material={materials.karkas}
                  position={[-0.00000458, 0, 0]}
                />
              </group>
              <group name="LP12" position={[-0.00000553, 0, 0]}>
                <mesh
                  name="LP12_rocks_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.LP12_rocks_0.geometry}
                  material={materials.rocks}
                  position={[-0.00000458, 0, 0]}
                />
              </group>
              <group name="LP13" position={[-0.00000553, 0, 0]}>
                <mesh
                  name="LP13_rocks_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.LP13_rocks_0.geometry}
                  material={materials.rocks}
                  position={[-0.00000458, 0, 0]}
                />
              </group>
              <group name="LP14" position={[-0.00000553, 0, 0]}>
                <mesh
                  name="LP14_rocks_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.LP14_rocks_0.geometry}
                  material={materials.rocks}
                  position={[-0.00000458, 0, 0]}
                />
              </group>
              <group name="LP15" position={[-0.00000553, 0, 0]}>
                <mesh
                  name="LP15_props_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.LP15_props_0.geometry}
                  material={materials.props}
                  position={[-0.00000458, 0, 0]}
                />
              </group>
              <group name="LP16" position={[-0.00000553, 0, 0]}>
                <mesh
                  name="LP16_props_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.LP16_props_0.geometry}
                  material={materials.props}
                  position={[-0.00000458, 0, 0]}
                />
              </group>
              <group name="LP17" position={[-0.00000553, 0, 0]}>
                <mesh
                  name="LP17_rocks_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.LP17_rocks_0.geometry}
                  material={materials.rocks}
                  position={[-0.00000458, 0, 0]}
                />
              </group>
              <group name="LP18" position={[-0.00000553, 0, 0]}>
                <mesh
                  name="LP18_roof1_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.LP18_roof1_0.geometry}
                  material={materials.roof1}
                  position={[-0.00000458, 0, 0]}
                />
              </group>
              <group name="LP19" position={[-0.00000553, 0, 0]}>
                <mesh
                  name="LP19_roof1_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.LP19_roof1_0.geometry}
                  material={materials.roof1}
                  position={[-0.00000458, 0, 0]}
                />
              </group>
              <group name="LP2" position={[-0.00000553, 0, 0]} />
              <group name="LP20" position={[-0.00000553, 0, 0]}>
                <mesh
                  name="LP20_roof1_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.LP20_roof1_0.geometry}
                  material={materials.roof1}
                  position={[-0.00000458, 0, 0]}
                />
              </group>
              <group name="LP21" position={[-0.00000553, 0, 0]}>
                <mesh
                  name="LP21_roof1_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.LP21_roof1_0.geometry}
                  material={materials.roof1}
                  position={[-0.00000458, 0, 0]}
                />
              </group>
              <group name="LP22" position={[-0.00000553, 0, 0]}>
                <mesh
                  name="LP22_roof2_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.LP22_roof2_0.geometry}
                  material={materials.roof2}
                  position={[-0.00000458, 0, 0]}
                />
              </group>
              <group name="LP23" position={[-0.00000553, 0, 0]}>
                <mesh
                  name="LP23_roof2_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.LP23_roof2_0.geometry}
                  material={materials.roof2}
                  position={[-0.00000458, 0, 0]}
                />
              </group>
              <group name="LP24" position={[-0.00000553, 0, 0]}>
                <mesh
                  name="LP24_roof2_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.LP24_roof2_0.geometry}
                  material={materials.roof2}
                  position={[-0.00000458, 0, 0]}
                />
              </group>
              <group name="LP25" position={[-0.00000553, 0, 0]}>
                <mesh
                  name="LP25_roof2_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.LP25_roof2_0.geometry}
                  material={materials.roof2}
                  position={[-0.00000458, 0, 0]}
                />
              </group>
              <group name="LP26" position={[-0.00000553, 0, 0]}>
                <mesh
                  name="LP26_roof2_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.LP26_roof2_0.geometry}
                  material={materials.roof2}
                  position={[-0.00000458, 0, 0]}
                />
              </group>
              <group name="LP27" position={[-0.00000553, 0, 0]}>
                <mesh
                  name="LP27_props_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.LP27_props_0.geometry}
                  material={materials.props}
                  position={[-0.00000458, 0, 0]}
                />
              </group>
              <group name="LP28" position={[-0.00000553, 0, 0]}>
                <mesh
                  name="LP28_props_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.LP28_props_0.geometry}
                  material={materials.props}
                  position={[-0.00000458, 0, 0]}
                />
              </group>
              <group name="LP29" position={[-0.00000553, 0, 0]}>
                <mesh
                  name="LP29_props_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.LP29_props_0.geometry}
                  material={materials.props}
                  position={[-0.00000458, 0, 0]}
                />
              </group>
              <group name="LP3" position={[-0.00000553, 0, 0]}>
                <mesh
                  name="LP3_karkas_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.LP3_karkas_0.geometry}
                  material={materials.karkas}
                  position={[-0.00000458, 0, 0]}
                />
              </group>
              <group name="LP30" position={[-0.00000553, 0, 0]}>
                <mesh
                  name="LP30_drova_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.LP30_drova_0.geometry}
                  material={materials.drova}
                  position={[-0.00000458, 0, 0]}
                />
              </group>
              <group name="LP31" position={[-0.00000553, 0, 0]}>
                <mesh
                  name="LP31_drova_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.LP31_drova_0.geometry}
                  material={materials.drova}
                  position={[-0.00000458, 0, 0]}
                />
              </group>
              <group name="LP32" position={[-0.00000553, 0, 0]}>
                <mesh
                  name="LP32_drova_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.LP32_drova_0.geometry}
                  material={materials.drova}
                  position={[-0.00000458, 0, 0]}
                />
              </group>
              <group name="LP33" position={[-0.00000553, 0, 0]}>
                <mesh
                  name="LP33_drova_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.LP33_drova_0.geometry}
                  material={materials.drova}
                  position={[-0.00000458, 0, 0]}
                />
              </group>
              <group name="LP34" position={[-0.00000553, 0, 0]}>
                <mesh
                  name="LP34_drova_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.LP34_drova_0.geometry}
                  material={materials.drova}
                  position={[-0.00000458, 0, 0]}
                />
              </group>
              <group name="LP4" position={[-0.00000553, 0, 0]}>
                <mesh
                  name="LP4_house_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.LP4_house_0.geometry}
                  material={materials.house}
                  position={[-0.00000458, 0, 0]}
                />
              </group>
              <group name="LP5" position={[-0.00000553, 0, 0]}>
                <mesh
                  name="LP5_karkas_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.LP5_karkas_0.geometry}
                  material={materials.karkas}
                  position={[-0.00000458, 0, 0]}
                />
              </group>
              <group name="LP6" position={[-0.00000553, 0, 0]}>
                <mesh
                  name="LP6_ground_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.LP6_ground_0.geometry}
                  material={materials.ground}
                  position={[-0.00000458, 0, 0]}
                />
              </group>
              <group name="LP7" position={[-0.00000553, 0, 0]}>
                <mesh
                  name="LP7_karkas_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.LP7_karkas_0.geometry}
                  material={materials.karkas}
                  position={[-0.00000458, 0, 0]}
                />
              </group>
              <group name="LP8" position={[-0.00000553, 0, 0]}>
                <mesh
                  name="LP8_karkas_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.LP8_karkas_0.geometry}
                  material={materials.karkas}
                  position={[-0.00000458, 0, 0]}
                />
              </group>
              <group name="LP9" position={[-0.00000553, 0, 0]}>
                <mesh
                  name="LP9_karkas_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.LP9_karkas_0.geometry}
                  material={materials.karkas}
                  position={[-0.00000458, 0, 0]}
                />
              </group>
            </group>
          </group>
        </group>
        <group
          name="Sketchfab_model002"
          position={[-43.92156982, 3.46585846, 10.95088482]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[0.90024573, 0.89357787, 0.72272784]}
        >
          <group name="root" position={[0.00000381, 0, 0]}>
            <group
              name="GLTF_SceneRootNode"
              position={[0.00000381, 0, 0]}
              rotation={[Math.PI / 2, 0, 0]}
            >
              <group name="Cube003_22" position={[0, 1.05240595, 0]}>
                <mesh
                  name="Object_34"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_34.geometry}
                  material={materials["Material.027"]}
                />
              </group>
              <group
                name="door1_13"
                position={[-5.47906494, 3.34968996, 1.48246336]}
                rotation={[0, 0, -0.09591252]}
                scale={[0.7732783, 0.77327836, 0.7732783]}
              >
                <mesh
                  name="Object_18"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_18.geometry}
                  material={materials["Material.009"]}
                  position={[-0.00001192, 0, 0]}
                />
              </group>
              <group
                name="door2_14"
                position={[-5.47906494, 3.34968996, 1.48246336]}
                rotation={[0, 0, -0.09591252]}
                scale={[0.7732783, 0.77327836, 0.7732783]}
              >
                <mesh
                  name="Object_20"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_20.geometry}
                  material={materials["Material.010"]}
                  position={[-0.00001192, 0, 0]}
                />
              </group>
              <group name="flag_11" position={[0, 1.05240595, 0]}>
                <mesh
                  name="Object_14"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_14.geometry}
                  material={materials["Material.008"]}
                />
              </group>
              <group name="grass_7" position={[0, 1.05240595, 0]} />
              <group name="peana_12" position={[0, 1.05240595, 0]} />
              <group
                name="pom_15"
                position={[0, 16.1059227, 0]}
                scale={3.29026937}
              >
                <mesh
                  name="Object_22"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_22.geometry}
                  material={materials["Material.011"]}
                />
              </group>
              <group
                name="portapedra1_18"
                position={[-5.47906494, 3.34968996, 1.48246336]}
                rotation={[0, 0, -0.09591252]}
                scale={[0.7732783, 0.77327836, 0.7732783]}
              >
                <mesh
                  name="Object_28"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_28.geometry}
                  material={materials["Material.013"]}
                  position={[-0.00001192, 0, 0]}
                />
              </group>
              <group
                name="portapedra2_20"
                position={[-5.47906494, 3.34968996, 1.48246336]}
                rotation={[0, 0, -0.09591252]}
                scale={[0.7732783, 0.77327836, 0.7732783]}
              >
                <mesh
                  name="Object_30"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_30.geometry}
                  material={materials["Material.012"]}
                  position={[-0.00001192, 0, 0]}
                />
              </group>
              <group name="rockdf1_8" position={[0, 1.05240595, 0]}>
                <mesh
                  name="Object_8"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_8.geometry}
                  material={materials["Material.003"]}
                  rotation={[0.01165021, -0.06147247, 0.18742136]}
                />
              </group>
              <group name="rocksf2_9" position={[0, 1.05240595, 0]}>
                <mesh
                  name="Object_10"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_10.geometry}
                  material={materials["Material.004"]}
                  rotation={[0, 0, 0.17721436]}
                />
              </group>
              <group name="rocksf3_10" position={[0, 1.05240595, 0]}>
                <mesh
                  name="Object_12"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_12.geometry}
                  material={materials["Material.002"]}
                  rotation={[0, 0, 0.16047354]}
                />
              </group>
              <group name="tower002_27" position={[0, 1.05240595, 0]}>
                <mesh
                  name="Object_44"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_44.geometry}
                  material={materials["Material.036"]}
                />
              </group>
              <group
                name="trampilla1_16"
                position={[0, 16.1059227, 0]}
                scale={3.29026937}
              >
                <mesh
                  name="Object_24"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_24.geometry}
                  material={materials["Material.015"]}
                />
              </group>
              <group
                name="trampilla2_17"
                position={[0, 16.1059227, 0]}
                scale={3.29026937}
              >
                <mesh
                  name="Object_26"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_26.geometry}
                  material={materials["Material.014"]}
                />
              </group>
              <group
                name="tree_6"
                position={[0, 16.1059227, 0]}
                scale={3.29026937}
              >
                <mesh
                  name="Object_4"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_4.geometry}
                  material={materials["Material.020"]}
                />
              </group>
              <group name="trees001_26" position={[0, 1.05240595, 0]}>
                <mesh
                  name="Object_42"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_42.geometry}
                  material={materials["Material.005"]}
                />
              </group>
              <group name="trees_21" position={[0, 1.05240595, 0]} />
              <group name="treess_25" position={[0, 1.05240595, 0]}>
                <mesh
                  name="Object_40"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_40.geometry}
                  material={materials.material_0}
                />
              </group>
              <group name="trunk_24" position={[0, 1.05240595, 0]} />
              <group name="trunks_23" position={[0, 1.05240595, 0]} />
            </group>
          </group>
        </group>
        <group
          name="Sketchfab_model003"
          position={[-15.10794067, 2.42351007, -45.71808243]}
          rotation={[-1.57683077, -6e-8, 2.83086275]}
          scale={[2.16455507, 2.16456056, 2.35403633]}
        >
          <group
            name="219ca6a250804ea2a660194b936f349dfbx"
            rotation={[Math.PI / 2, 0, 0]}
          >
            <group name="RootNode002">
              <group
                name="group"
                position={[0.00113408, -0.11697869, -2.63469362]}
                rotation={[-0.2841431, 0, 0]}
                scale={[1.04674029, 0.96027213, 0.84018362]}
              >
                <group name="pasted__LOW">
                  <group name="pasted__pCube4">
                    <mesh
                      name="pasted__pCube4_Kist_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.pasted__pCube4_Kist_0.geometry}
                      material={materials.Kist}
                    />
                  </group>
                  <group name="pasted__pCube5">
                    <mesh
                      name="pasted__pCube5_Kist_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.pasted__pCube5_Kist_0.geometry}
                      material={materials.Kist}
                    />
                  </group>
                  <group name="pasted__pCube6">
                    <mesh
                      name="pasted__pCube6_Kist_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.pasted__pCube6_Kist_0.geometry}
                      material={materials.Kist}
                    />
                  </group>
                  <group name="pasted__polySurface10">
                    <mesh
                      name="pasted__polySurface10_Kist_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.pasted__polySurface10_Kist_0.geometry}
                      material={materials.Kist}
                    />
                  </group>
                  <group name="pasted__polySurface11">
                    <mesh
                      name="pasted__polySurface11_Kist_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.pasted__polySurface11_Kist_0.geometry}
                      material={materials.Kist}
                    />
                  </group>
                </group>
              </group>
              <group
                name="group2001"
                position={[-0.80589855, 1.03155231, 0.45955503]}
                rotation={[-1.54396324, 0.69471558, 1.52256256]}
                scale={[0.09191868, 0.09191871, 0.0919187]}
              >
                <group
                  name="pasted__low001"
                  position={[-0.00004153, -0.00000954, 0.00000572]}
                >
                  <mesh
                    name="pasted__low_zwaard_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pasted__low_zwaard_0.geometry}
                    material={materials.zwaard}
                    position={[-0.000032, 0.00001621, -0.00000381]}
                  />
                </group>
                <group
                  name="pasted__pCylinder1"
                  position={[-0.00004153, -0.00000954, 0.00000572]}
                >
                  <mesh
                    name="pasted__pCylinder1_zwaard_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pasted__pCylinder1_zwaard_0.geometry}
                    material={materials.zwaard}
                    position={[-0.000032, 0.00001621, -0.00000381]}
                  />
                </group>
                <group
                  name="pasted__pSphere4"
                  position={[-0.00004153, -0.00000954, 0.00000572]}
                >
                  <mesh
                    name="pasted__pSphere4_zwaard_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pasted__pSphere4_zwaard_0.geometry}
                    material={materials.zwaard}
                    position={[-0.000032, 0.00001621, -0.00000381]}
                  />
                </group>
                <group
                  name="pasted__pTorus1"
                  position={[-0.00004153, -0.00000954, 0.00000572]}
                >
                  <mesh
                    name="pasted__pTorus1_zwaard_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pasted__pTorus1_zwaard_0.geometry}
                    material={materials.zwaard}
                    position={[-0.000032, 0.00001621, -0.00000381]}
                  />
                </group>
                <group
                  name="pasted__pTorus2"
                  position={[-0.00004153, -0.00000954, 0.00000572]}
                >
                  <mesh
                    name="pasted__pTorus2_zwaard_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pasted__pTorus2_zwaard_0.geometry}
                    material={materials.zwaard}
                    position={[-0.000032, 0.00001621, -0.00000381]}
                  />
                </group>
              </group>
              <group name="pDisc1001" scale={[1, 0.77331114, 1]} />
              <group name="pDisc2" />
              <group
                name="STENEN"
                position={[0.4255363, 0.25241873, -0.09709767]}
                scale={[0.20394696, 0.15832518, 0.20394693]}
              >
                <group
                  name="pasted__low"
                  position={[0.00000455, 0, 0.00003668]}
                >
                  <mesh
                    name="pasted__low_steen_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pasted__low_steen_0.geometry}
                    material={materials.steen}
                    position={[0.00001027, 0, 0.00002142]}
                  />
                </group>
                <group
                  name="pasted__low1"
                  position={[0.00000455, 0, 0.00003668]}
                >
                  <mesh
                    name="pasted__low1_steen_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pasted__low1_steen_0.geometry}
                    material={materials.steen}
                    position={[0.00001027, 0, 0.00002142]}
                  />
                </group>
                <group
                  name="pasted__low2"
                  position={[0.00000455, 0, 0.00003668]}
                >
                  <mesh
                    name="pasted__low2_steen_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pasted__low2_steen_0.geometry}
                    material={materials.steen}
                    position={[0.00001027, 0, 0.00002142]}
                  />
                </group>
                <group
                  name="pasted__low3"
                  position={[0.00000455, 0, 0.00003668]}
                >
                  <mesh
                    name="pasted__low3_steen_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pasted__low3_steen_0.geometry}
                    material={materials.steen}
                    position={[0.00001027, 0, 0.00002142]}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
        <group
          name="Sketchfab_model004"
          position={[-11.23770332, 3.22911978, -46.39205933]}
          rotation={[-1.66131613, 0, 2.91074069]}
          scale={2.75}
        >
          <group name="Root">
            <group name="Cube002" scale={[0.24462993, 0.24462998, 0.21981998]}>
              <mesh
                name="Cube002_0"
                castShadow
                receiveShadow
                geometry={nodes.Cube002_0.geometry}
                material={materials.color}
                position={[0, 0.00000638, 0]}
                rotation={[-0.06459555, -0.01517485, -0.00049029]}
              />
            </group>
            <group
              name="Hemi"
              position={[-7.09745979, 3.30791259, 10.42972755]}
              rotation={[0.55445234, -0.23449773, 1.57295068]}
              scale={[1.34161878, 1.34161115, 1.34161651]}
            >
              <group name="Hemi001" />
            </group>
            <group
              name="Hemi002"
              position={[-5.02666903, -12.8042202, 15.36496735]}
              rotation={[0.91716122, -0.31055417, 1.47472297]}
              scale={[1.34161282, 1.34161782, 1.3416146]}
            >
              <group name="Hemi003" />
            </group>
          </group>
        </group>
        <group
          name="bfb1ea86655f4c4ab4c6cbbb449cedf4fbx"
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <group name="Object_2">
            <group name="RootNode003">
              <group name="BirdOrange_all">
                <group name="Geometry">
                  <group name="BirdOrange" />
                </group>
                <group name="Main" />
              </group>
            </group>
          </group>
        </group>
        <group name="Object_50" />
        <group name="RootNode004">
          <group name="socha_06_kampa" rotation={[-Math.PI / 2, 0, 0]} />
        </group>
        <group
          name="Sketchfab_model005"
          position={[-8.09470177, 1.50147152, 54.97930527]}
          rotation={[-Math.PI / 2, -9e-8, 1.06936607]}
          scale={[1.30000007, 1.50000012, 1.30000007]}
        >
          <group name="guybrushobjcleanermaterialmergergles">
            <mesh
              name="Object_2001"
              castShadow
              receiveShadow
              geometry={nodes.Object_2001.geometry}
              material={materials["Material.018"]}
              position={[-0.16813633, -0.09216577, 1.20582724]}
              rotation={[0.02941064, 0.05572129, 0.08457674]}
            />
          </group>
        </group>
        <group
          name="Sketchfab_model006"
          position={[-8.62873459, 0.76750386, 62.62255096]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={3.5}
        >
          <group name="Boat_Aobjcleanermaterialmergergles">
            <mesh
              name="Object_10001"
              castShadow
              receiveShadow
              geometry={nodes.Object_10001.geometry}
              material={materials.acmat_3}
            />
            <mesh
              name="Object_11"
              castShadow
              receiveShadow
              geometry={nodes.Object_11.geometry}
              material={materials.acmat_0}
            />
            <mesh
              name="Object_12001"
              castShadow
              receiveShadow
              geometry={nodes.Object_12001.geometry}
              material={materials.acmat_0}
            />
            <mesh
              name="Object_13"
              castShadow
              receiveShadow
              geometry={nodes.Object_13.geometry}
              material={materials.acmat_0}
            />
            <mesh
              name="Object_14001"
              castShadow
              receiveShadow
              geometry={nodes.Object_14001.geometry}
              material={materials.acmat_0}
            />
            <mesh
              name="Object_15"
              castShadow
              receiveShadow
              geometry={nodes.Object_15.geometry}
              material={materials.acmat_1}
            />
            <mesh
              name="Object_16"
              castShadow
              receiveShadow
              geometry={nodes.Object_16.geometry}
              material={materials.acmat_10}
            />
            <mesh
              name="Object_17"
              castShadow
              receiveShadow
              geometry={nodes.Object_17.geometry}
              material={materials.acmat_10}
            />
            <mesh
              name="Object_18001"
              castShadow
              receiveShadow
              geometry={nodes.Object_18001.geometry}
              material={materials.acmat_10}
            />
            <mesh
              name="Object_19"
              castShadow
              receiveShadow
              geometry={nodes.Object_19.geometry}
              material={materials.acmat_11}
            />
            <mesh
              name="Object_2002"
              castShadow
              receiveShadow
              geometry={nodes.Object_2002.geometry}
              material={materials.acmat_17}
            />
            <mesh
              name="Object_20001"
              castShadow
              receiveShadow
              geometry={nodes.Object_20001.geometry}
              material={materials.acmat_11}
            />
            <mesh
              name="Object_21"
              castShadow
              receiveShadow
              geometry={nodes.Object_21.geometry}
              material={materials.acmat_11}
            />
            <mesh
              name="Object_22001"
              castShadow
              receiveShadow
              geometry={nodes.Object_22001.geometry}
              material={materials.acmat_12}
            />
            <mesh
              name="Object_23"
              castShadow
              receiveShadow
              geometry={nodes.Object_23.geometry}
              material={materials.acmat_13}
            />
            <mesh
              name="Object_24001"
              castShadow
              receiveShadow
              geometry={nodes.Object_24001.geometry}
              material={materials.acmat_13}
            />
            <mesh
              name="Object_25"
              castShadow
              receiveShadow
              geometry={nodes.Object_25.geometry}
              material={materials.acmat_13}
            />
            <mesh
              name="Object_26001"
              castShadow
              receiveShadow
              geometry={nodes.Object_26001.geometry}
              material={materials.acmat_14}
            />
            <mesh
              name="Object_27"
              castShadow
              receiveShadow
              geometry={nodes.Object_27.geometry}
              material={materials.acmat_14}
            />
            <mesh
              name="Object_28001"
              castShadow
              receiveShadow
              geometry={nodes.Object_28001.geometry}
              material={materials.acmat_15}
            />
            <mesh
              name="Object_29"
              castShadow
              receiveShadow
              geometry={nodes.Object_29.geometry}
              material={materials.acmat_6}
            />
            <mesh
              name="Object_3"
              castShadow
              receiveShadow
              geometry={nodes.Object_3.geometry}
              material={materials.acmat_18}
            />
            <mesh
              name="Object_30001"
              castShadow
              receiveShadow
              geometry={nodes.Object_30001.geometry}
              material={materials.acmat_7}
            />
            <mesh
              name="Object_31"
              castShadow
              receiveShadow
              geometry={nodes.Object_31.geometry}
              material={materials.acmat_8}
            />
            <mesh
              name="Object_32"
              castShadow
              receiveShadow
              geometry={nodes.Object_32.geometry}
              material={materials.acmat_9}
            />
            <mesh
              name="Object_33"
              castShadow
              receiveShadow
              geometry={nodes.Object_33.geometry}
              material={materials.acmat_2}
            />
            <mesh
              name="Object_34001"
              castShadow
              receiveShadow
              geometry={nodes.Object_34001.geometry}
              material={materials.acmat_4}
            />
            <mesh
              name="Object_35"
              castShadow
              receiveShadow
              geometry={nodes.Object_35.geometry}
              material={materials.acmat_5}
            />
            <mesh
              name="Object_4001"
              castShadow
              receiveShadow
              geometry={nodes.Object_4001.geometry}
              material={materials.acmat_19}
            />
            <mesh
              name="Object_5"
              castShadow
              receiveShadow
              geometry={nodes.Object_5.geometry}
              material={materials.acmat_16}
            />
            <mesh
              name="Object_6"
              castShadow
              receiveShadow
              geometry={nodes.Object_6.geometry}
              material={materials.acmat_20}
            />
            <mesh
              name="Object_7"
              castShadow
              receiveShadow
              geometry={nodes.Object_7.geometry}
              material={materials.acmat_21}
            />
            <mesh
              name="Object_8001"
              castShadow
              receiveShadow
              geometry={nodes.Object_8001.geometry}
              material={materials.acmat_22}
            />
            <mesh
              name="Object_9"
              castShadow
              receiveShadow
              geometry={nodes.Object_9.geometry}
              material={materials.acmat_23}
            />
          </group>
        </group>
        <group
          name="Sketchfab_model007"
          position={[-11.6038208, 2.99281716, 56.46776199]}
          rotation={[-1.51239905, 0, 0]}
          scale={0.0025}
        >
          <group
            name="07aa4421be714ea482d81d1708d73df0fbx"
            position={[-0.00146484, 0.00006104, -0.00036621]}
            rotation={[Math.PI / 2, 0, 0]}
          >
            <group
              name="RootNode005"
              position={[0.00048828, 0.00048828, 0.00150299]}
            >
              <group
                name="Mesh"
                position={[0.00048828, 0.00048828, -0.00244141]}
              >
                <mesh
                  name="Mesh_LPDog_M_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh_LPDog_M_0.geometry}
                  material={materials.LPDog_M}
                  position={[0.00048828, 0.00024414, -0.00050354]}
                />
              </group>
            </group>
          </group>
        </group>
        <group
          name="Sketchfab_model008"
          position={[-11.7389822, 8.00051689, -34.36624527]}
          rotation={[-Math.PI / 2, -1.7e-7, 1.80306874]}
          scale={[4.1886425, 6.22942162, 6.24255943]}
        >
          <group
            name="Collada_visual_scene_group"
            rotation={[Math.PI / 2, 0, 0]}
          >
            <group name="defaultobject" />
          </group>
        </group>
        <group
          name="Sketchfab_model009"
          position={[-18.62507248, 1.63656127, -32.53393173]}
          rotation={[-Math.PI / 2, 3e-8, -0.57045282]}
          scale={[0.003, 0.0035, 0.003]}
        >
          <group
            name="5f8303813aa64857bddf126cb051dbeafbx"
            position={[0.00001511, 0.00020039, -0.00005937]}
            rotation={[Math.PI / 2, 0, 0]}
          >
            <group
              name="RootNode006"
              position={[-0.00144974, -0.00003304, -0.00109808]}
            >
              <group
                name="Door"
                position={[513.09143066, 4189.70996094, -316.83895874]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={[18.77359772, 18.7735939, 18.773592]}
              >
                <mesh
                  name="Door_Texture001_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Door_Texture001_0.geometry}
                  material={materials["Texture.001"]}
                  position={[-0.00000827, -0.00000497, 0.0000191]}
                />
              </group>
              <group
                name="Glowing_Crystals"
                position={[720.31054688, -719.41357422, -308.07833862]}
                rotation={[-0.81526022, -0.16831245, 0.42182915]}
                scale={[100.00002289, 100.00000763, 100.00000763]}
              >
                <mesh
                  name="Glowing_Crystals__0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Glowing_Crystals__0.geometry}
                  material={materials.Glowing_Crystals__0}
                  position={[0, 0, -0.00000608]}
                />
              </group>
              <group
                name="House"
                position={[56.87953186, 4443.14550781, -176.33314514]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={[203.24581909, 203.24578857, 203.24578857]}
              >
                <mesh
                  name="House_Texture001_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.House_Texture001_0.geometry}
                  material={materials["Texture.001"]}
                  position={[-0.00000313, 0, 0]}
                />
              </group>
              <group
                name="House_Frame"
                position={[213.31994629, 3983.07250977, 625.95135498]}
                rotation={[-Math.PI / 2, -0.93533296, -Math.PI]}
                scale={[34.74195099, 41.60268021, 39.52824783]}
              >
                <mesh
                  name="House_Frame_Texture001_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.House_Frame_Texture001_0.geometry}
                  material={materials["Texture.001"]}
                  position={[0, -0.00001111, -0.00000763]}
                />
              </group>
              <group
                name="Island"
                position={[23.91993713, -24.45090485, -14.69225502]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={[1269.70495605, 1269.70483398, 416.3600769]}
              >
                <mesh
                  name="Island_Texture001_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Island_Texture001_0.geometry}
                  material={materials["Texture.001"]}
                />
              </group>
              <group
                name="Ladder"
                position={[935.73980713, 1780.65100098, -294.03591919]}
                rotation={[Math.PI, -9e-8, Math.PI / 2]}
                scale={[14.68029881, 14.68030071, 14.68029976]}
              >
                <mesh
                  name="Ladder_Texture001_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Ladder_Texture001_0.geometry}
                  material={materials["Texture.001"]}
                  position={[0.00003311, -0.00003272, 0.00009872]}
                />
              </group>
              <group
                name="Leaves"
                position={[-1841.93151855, 4958.15283203, -1234.84765625]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={[147.11627197, 147.1162262, 147.1162262]}
              >
                <mesh
                  name="Leaves_Texture001_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Leaves_Texture001_0.geometry}
                  material={materials["Texture.001"]}
                  position={[0.00000485, -0.00001635, 0.00000614]}
                />
              </group>
              <group
                name="Platform_1"
                position={[737.66265869, 1794.90710449, 816.44476318]}
                rotation={[-Math.PI / 2, -6e-8, Math.PI / 2]}
                scale={[22.54063225, 37.17212677, 14.68030262]}
              >
                <mesh
                  name="Platform_1_Texture001_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Platform_1_Texture001_0.geometry}
                  material={materials["Texture.001"]}
                  position={[-0.00001214, -0.00002076, 0.000029]}
                />
              </group>
              <group
                name="Platform_2"
                position={[142.74423218, 2685.66503906, 155.05641174]}
                rotation={[-1.2106779, 0.49527424, -1.71216588]}
                scale={[71.53083038, 71.53079987, 111.45067596]}
              >
                <mesh
                  name="Platform_2_Texture001_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Platform_2_Texture001_0.geometry}
                  material={materials["Texture.001"]}
                  position={[0.00000763, 0, 0]}
                />
              </group>
              <group
                name="Roof"
                position={[-211.96762085, 5182.97216797, -176.99908447]}
                rotation={[-Math.PI / 2, 0.70889354, -Math.PI]}
                scale={[15.94793606, 61.54153824, 269.94168091]}
              >
                <mesh
                  name="Roof_Texture001_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Roof_Texture001_0.geometry}
                  material={materials["Texture.001"]}
                  position={[0.00007629, 0.00002097, -0.00000286]}
                />
              </group>
              <group
                name="Stairs"
                position={[18.53274918, 688.07366943, 324.40866089]}
                rotation={[-Math.PI / 2, 0.62439615, -7e-8]}
                scale={[99.99997711, 99.99999237, 99.99997711]}
              >
                <mesh
                  name="Stairs_Texture001_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Stairs_Texture001_0.geometry}
                  material={materials["Texture.001"]}
                  position={[0, 0.00001576, 0]}
                />
              </group>
              <group
                name="Stones"
                position={[23.91993713, -24.45090485, -14.69225502]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={[1269.70495605, 1269.70483398, 416.3600769]}
              >
                <mesh
                  name="Stones_Texture001_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Stones_Texture001_0.geometry}
                  material={materials["Texture.001"]}
                />
              </group>
              <group
                name="Tree"
                position={[-0.00094477, 602.43426514, -0.00074399]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={[99.99998474, 99.99997711, 99.99997711]}
              >
                <mesh
                  name="Tree_Texture001_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Tree_Texture001_0.geometry}
                  material={materials["Texture.001"]}
                  position={[-0.00000731, 0.00000862, 0]}
                />
              </group>
              <group
                name="Windows"
                position={[56.87953186, 4443.14550781, -176.33314514]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={[203.24581909, 203.24578857, 203.24578857]}
              >
                <mesh
                  name="Windows_Texture001_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Windows_Texture001_0.geometry}
                  material={materials["Texture.001"]}
                  position={[-0.00000313, 0, 0]}
                />
              </group>
            </group>
          </group>
        </group>
        <group
          name="Sketchfab_model001"
          position={[28.55756187, -4.75106096, -44.04545975]}
          rotation={[-Math.PI / 2, 3e-8, -2.50973322]}
          scale={[0.40000004, 0.40000004, 0.40000001]}
        >
          <group name="VoxRoot" position={[-0.00000422, 0, 0]}>
            <group name="VoxTransform" position={[-0.00000422, 0, 0]}>
              <group name="VoxGroup" position={[-0.00000422, 0, 0]}>
                <group
                  name="VoxTransform001"
                  position={[-0.00000354, 0, 20.00000191]}
                >
                  <mesh
                    name="Object_10002"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_10002.geometry}
                    material={materials.VoxMaterial_59}
                    position={[-0.00000354, 0, 0]}
                  />
                  <mesh
                    name="Object_5001"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_5001.geometry}
                    material={materials.VoxMaterial_2}
                    position={[-0.00000354, 0, 0]}
                  />
                  <mesh
                    name="Object_6001"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_6001.geometry}
                    material={materials.VoxMaterial_6}
                    position={[-0.00000354, 0, 0]}
                  />
                  <mesh
                    name="Object_7001"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_7001.geometry}
                    material={materials.VoxMaterial_9}
                    position={[-0.00000354, 0, 0]}
                  />
                  <mesh
                    name="Object_8002"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_8002.geometry}
                    material={materials.VoxMaterial_10}
                    position={[-0.00000354, 0, 0]}
                  />
                  <mesh
                    name="Object_9001"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_9001.geometry}
                    material={materials.VoxMaterial_39}
                    position={[-0.00000354, 0, 0]}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload(islandScene);
export default Island;