/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: InfDev (https://sketchfab.com/InfDev)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-plane-with-animation-78282ac2c7a64dd8a7f39cffd9e201d7
Title: Low Poly Plane With Animation
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import planeGlb from '../assets/3D/plane.glb';
const Plane = ({isRotating, ...props})=> {
  const planeRef = useRef();
  const { nodes, materials, animations } = useGLTF(
    planeGlb
  );
  const { actions, names } = useAnimations(animations, planeRef);
  console.log(actions,names);
  useEffect(()=>{
        actions[names[0]].play();
  })
  return (
    <group ref={planeRef} {...props}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group
                name="Cylinder_0"
                position={[0, 3.997, 0]}
                rotation={[-Math.PI / 2, -0.001, 0]}
              >
                <mesh
                  name="Object_4"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_4.geometry}
                  material={materials.material}
                />
                <mesh
                  name="Object_5"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_5.geometry}
                  material={materials.Yellow}
                />
                <mesh
                  name="Object_6"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_6.geometry}
                  material={materials.Blue}
                />
                <mesh
                  name="Object_7"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_7.geometry}
                  material={materials.Grey}
                />
              </group>
              <group
                name="Cylinder001_1"
                position={[0, 3.997, 1.683]}
                rotation={[Math.PI / 2, 0, 0]}
              >
                <mesh
                  name="Object_9"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_9.geometry}
                  material={materials.Yellow}
                />
                <mesh
                  name="Object_10"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_10.geometry}
                  material={materials.Grey}
                />
                <mesh
                  name="Object_11"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_11.geometry}
                  material={materials.material}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload(planeGlb);
export default Plane;
